# Generated by Django 4.1.2 on 2022-10-23 04:27

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('add_date', models.DateField(auto_now_add=True, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='category')),
                ('url', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField()),
                ('post_author', models.CharField(default='NSP', max_length=50)),
                ('post_description', models.TextField(max_length=500, null=True)),
                ('url', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(upload_to='posts')),
                ('file', models.FileField(null=True, upload_to='files')),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('post_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
