# Generated by Django 4.0.5 on 2022-07-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
