# Generated by Django 4.0.5 on 2022-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_posts_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
