# Generated by Django 4.0.5 on 2022-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_posts_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
