# Generated by Django 4.0.5 on 2022-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_posts_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
