# Generated by Django 4.0.5 on 2022-07-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
