# Generated by Django 4.0.5 on 2022-07-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_posts_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
